name: Deploy Automatico su Aruba

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Sync files via Git-FTP
      uses: TestGithubUser/git-ftp-action@v1.0.0
      with:
        url: "ftp://ftp.smartindustries.it/sew4climb/"
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}