name: Deploy Automatico su Aruba

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Git-FTP
      run: sudo apt-get update && sudo apt-get install -y git-ftp

    - name: Sync files via Git-FTP
      run: |
        git ftp config --user "${{ secrets.FTP_USERNAME }}" --password "${{ secrets.FTP_PASSWORD }}" --syncroot . "ftp://ftp.smartindustries.it/sew4climb/"
        git ftp push --force || git ftp init